//=== Login =====
export const LOGIN_REQUEST = 'USERS_LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'USERS_LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'USERS_LOGIN_FAILURE';
export const LOGOUT = 'USERS_LOGOUT';
export const REGISTER_REQUEST = 'USERS_REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'USERS_REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'USERS_REGISTER_FAILURE'; 
//=== Alert ====
export const SUCCESS= 'ALERT_SUCCESS';
export const ERROR= 'ALERT_ERROR';
export const CLEAR= 'ALERT_CLEAR';
//==== User ====
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const INIT_CURRENT_USER = 'INIT_CURRENT_USER';
export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN';
export const SET_SIGNIN_RESULT = 'SET_SIGNIN_RESULT';
export const REHYDRATE = 'REHYDRATE';
//==== Post ====
export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_POST = 'FETCH_POST';
export const CREATE_POST = 'CREATE_POST';
export const UPDATE_POST = 'UPDATE_POST';
export const DELETE_POST = 'DELETE_POST';
export const FETCH_POSTS_DATA_FAILURE = "FETCH_POSTS_DATA_FAILURE";
